site_name: pybox

docs_dir: docs

theme:
  name: terminal
  palette:
    primary: red
  font:
    text: Ubuntu

markdown_extensions:
  - pymdownx.betterem

watch:
  - ./pybox


plugins:
- mkdocstrings:
    handlers:
      python:
        paths: [src]
        options:
          do_something: true
          heading_level: 2
          show_root_toc_entry: false
          show_root_full_path: false
          show_category_heading: true
          members_order: "source"
          docstring_section_style: "list"
          show_signature_annotations: true

extra_css:
  - stylesheets/extra.css

nav:
  - Index: index.md
  - Reference:  
    - Button Module: button.md
    - Led Module: led.md
    - Matrix Module: matrix.md
  - Exercises:
    - Button: tut_button.md
    - Led: tut_led.md
    - Matrix: tut_matrix.md
  - Exam:
    - Esercitazioni: esame.md
